export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const SELECT_PRODUCTO = "SELECT_PRODUCTO";
export const SELECT_PRODUCTO_EXITO = "SELECT_PRODUCTO_EXITO";
export const SELECT_PRODUCTO_ERROR = "SELECT_PRODUCTO";

export const DELETE_PRODUCTO = "DELETE_PRODUCTO";
export const DELETE_PRODUCTO_EXITO = "DELETE_PRODUCTO_EXITO";
export const DELETE_PRODUCTO_ERROR = "DELETE_PRODUCTO_ERROR";
