export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const SELECT_PRODUCTO = "SELECT_PRODUCTO";
export const SELECT_PRODUCTO_EXITO = "SELECT_PRODUCTO_EXITO";
export const SELECT_PRODUCTO_ERROR = "SELECT_PRODUCTO";

export const DELETE_PRODUCTO = "DELETE_PRODUCTO";
export const DELETE_PRODUCTO_EXITO = "DELETE_PRODUCTO_EXITO";
export const DELETE_PRODUCTO_ERROR = "DELETE_PRODUCTO_ERROR";
export const CANCELAR_DELETE_PRODUCTO = "CANCELAR_DELETE_PRODUCTO";

export const EDIT_PRODUCTO = "EDIT_PRODUCTO";
export const COMENZAR_EDIT_PRODUCTO = "COMENZAR_EDIT_PRODUCTO";
export const EDIT_PRODUCTO_EXITO = "EDIT_PRODUCTO_EXITO";
export const EDIT_PRODUCTO_ERROR = "EDIT_PRODUCTO_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
